// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:cbf1a9f5-b5a7-4747-b594-dde7581bb1d3',
    'aws_cognito_region': 'us-east-1',
    'aws_mobile_analytics_app_id': '2addb395d36049e68e4885136716c3bf',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '991df13c-c8ce-4fe0-8707-650dd2dc05c1',
    'aws_project_name': 'qnary_react',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'qnaryreact-mobilehub-2051767775',
}

export default awsmobile;
